title: IdeaCardsNFT
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
color_scheme: light
accent_color: blue
header:
  title: IDEACARDSNFT
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Press Release
      url: /press-release/
      style: link
    - label: Research Statement
      url: /research-statement/
      style: link
      icon: dribbble
      new_window: false
      no_follow: false
      type: action
footer:
  content: >-
    &copy; IdeaCardsNFT. All rights reserved. This Jamstack site was created
    with <a href="https://www.stackbit.com/?utm_source=deployed-footer"
    target="_blank" rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=exto&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
  has_social: true
  social_links:
    - label: ig
      url: 'https://www.instagram.com/ideacardsnft/'
      style: icon
      icon: instagram
      new_window: true
      no_follow: false
      type: action
    - label: email
      url: 'mailto:ideacardsnft@gmail.com'
      style: link
      icon: dribbble
      new_window: true
      no_follow: false
      type: action
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://ideacardsnft.github.io'
